[package]
name = "kokudaka_calculator"
version = "0.1.0"
authors = ["Sadaie Matsudaira <sadaie@matsuri-hi.me>"]
edition = "2018"

[dependencies]
stdweb = "0.4.11"
serde = "1.0.82"
serde_json = "1.0.33"
serde_derive = "1.0.82"
lazy_static = "1.2.0"
num-traits = "0.2.6"
